### ISSUE TITLE
Library in .var/app/<>/data / `XDG_DATA_HOME`.

### ISSUE THREAD

**Issue by jtagcat** [flathub/com.calibre_ebook.calibre#104]
```json
  "library_path": "${XDG_DATA_HOME}/library",
```

or anything else I tried doesn't work. Can the library directory use `XDG_DATA_HOME` in it?

**Comment by ghisvail** [comment]
I don't understand what you are reporting

**Comment by jtagcat** [comment]
I'd like to have the library located in `${XDG_DATA_HOME}/library` (`~/.var/app/com.calibre_ebook.calibre/data`).

**Comment by Erick555** [comment]
I think the path must be absolute so maybe try `"library_path": "/home/<username>/.var/app/com.calibre_ebook.calibre/data/library",`. You may also ask upstream for help as this isn't flatpak elated question.

**Comment by jtagcat** [comment]
Absolute path is a workaround, point being the location can change. I guess issue of upstream then. ¯\_(ツ)_/¯
