### ISSUE TITLE
Support aarch64

### ISSUE THREAD

**Issue by jwillikers** [flathub/com.calibre_ebook.calibre#107]
Would love to have support for `aarch64` devices.

**Comment by jwillikers** [comment]
I went ahead and submitted a bug upstream [here](https://bugs.launchpad.net/calibre/+bug/1945782) to provide binaries for `aarch64` since building from source isn't going to happen.

**Comment by AimVaguely** [comment]
They haven't updated the bug that you linked, but the [release notes for 6.0](https://calibre-ebook.com/whats-new) say "Support for new CPU architectures: Apple Silicon and ARM64 on Linux."

**Comment by ghisvail** [comment]
You are correct. There are ARM 64-bit binaries on the [release page](https://github.com/kovidgoyal/calibre/releases/tag/v6.0.0).

**Comment by ghisvail** [comment]
Could any of you try [this](https://github.com/flathub/com.calibre_ebook.calibre/pull/140#issuecomment-1180093587) and report whether it works on your `aarch64` devices? Thanks.
