### ISSUE TITLE
Update to the latest Calibre for new paperwhite support [2018 model]

### ISSUE THREAD

**Issue by japrogramer** [flathub/com.calibre_ebook.calibre#12]
Hello the current version of calibre on flathub does not support the latest kindle device
but there is an update in the latest version.
Please update the calibre package used to built this flatpack

**Comment by nedrichards** [comment]
That update is here: https://github.com/flathub/com.calibre_ebook.calibre/pull/11 just needs a little testing then it'll be out.

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/com.calibre_ebook.calibre/commit/aeafda77600886480f3a8a87409b42ea3feddfe1
