### ISSUE TITLE
Could not initialize GLX

### ISSUE THREAD

**Issue by clayote** [flathub/com.calibre_ebook.calibre#120]
Installed on Linux Mint 20.3 using `flatpak install com.calibre_ebook.calibre`

Then tried to run like `flatpak run com.calibre_ebook.calibre` and got this:

```
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
```

**Comment by Erick555** [comment]
What gpu do you have? You may try setting `export QT_XCB_GL_INTEGRATION=none` or `export QT_XCB_GL_INTEGRATION=xcb_egl` before launching flatpak.

**Comment by clayote** [comment]
I've got a Nvidia GTX 1060

Here's what happened with those env vars

```
sanotehu@sanotehu-MS-7A31:~/Downloads$ QT_XCB_GL_INTEGRATION=none flatpak run com.calibre_ebook.calibre
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Qt: Session management error: None of the authentication protocols specified are supported
sanotehu@sanotehu-MS-7A31:~/Downloads$ QT_XCB_GL_INTEGRATION=xcb_egl flatpak run com.calibre_ebook.calibre
libEGL warning: DRI2: failed to authenticate
Qt: Session management error: None of the authentication protocols specified are supported
```

**Comment by clayote** [comment]
It turns out that if I downgrade my video drivers all the way to nvidia-driver-390, `flatpak run com.calibre_ebook.calibre` works fine! I would prefer to use recent versions of them both, though.

**Comment by Erick555** [comment]
You need to download nvidia-driver-470 from flatpak (it should) be done automatically. If you have troubles then maybe ask for help [here](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia).

**Comment by clayote** [comment]
There does not seem to be any nvidia-470 package in flathub and I'll have to downgrade to nvidia-465 if I want to use calibre this way.

As this is not a bug with this package, I will close this issue.

**Comment by clayote** [comment]
Ok, that wasn't really true. The magic command was
`flatpak install org.freedesktop.Platform.GL.nvidia-470-86`
