### ISSUE TITLE
Use QT from KDE Flatpak runtime for input method support

### ISSUE THREAD

**Issue by ImBearChild** [flathub/com.calibre_ebook.calibre#126]
I've noticed that I can't type Chinese in flatpak version of calibre. The Chinese input method fcitx5 dosen't work. But Firefox in flatpak can use fcitx5 normally. I tried `flatpak override --user --talk-name=org.freedesktop.portal.Fcitx com.calibre_ebook.calibre` but no work.

**Comment by ImBearChild** [comment]
Current build of PyQT don't include input method support, please use QT library `org.kde.Platform` instead.

**Comment by ghisvail** [comment]
> Current build of PyQT don't include input method support

That could be an issue with the upstream Qt distribution provided upstream.

Pinging @kovidgoyal for input.

**Comment by kovidgoyal** [comment]
PyQt doesnt have input methods, Qt does. And the Qt in calibre is built
as seen here: https://github.com/kovidgoyal/bypy/blob/master/bypy/pkgs/qt_base.py

input method plugins are typically provided by the host OS based on
whatever input methods it has support for.

**Comment by ImBearChild** [comment]
> input method plugins are typically provided by the host OS based on
> whatever input methods it has support for.

As far as I know, in order to use input method, QT have to be compiled with input method support, since input method daemon on hosts talk with applications in flatpak via D-Bus. Input method plugins on hosts cannot be used for flatpak.

**Comment by kovidgoyal** [comment]
I have no clue about flatpaks, I am talking about the official calibre binaries, not flatpaks.

**Comment by ImBearChild** [comment]
> official calibre binaries

Yes, on official calibre binaries, it's true. Qt can use input method plugins from host OS, but that won't happen on flatpak. So flatpak should use a runtime which have input method plugins built in, for example, replace `org.kde.Platform` with `org.freedesktop.Platform`, a developer of Fcitx called csslayer told me that.

**Comment by ghisvail** [comment]
> replace org.kde.Platform with org.freedesktop.Platform

I am guessing you meant the opposite. I don't know whether calibre would use Qt provided by the Flatpak runtime over its own embedded copy in this case though.

**Comment by Erick555** [comment]
Could you try running `flatpak run --runtime=org.kde.Platform//5.15-21.08 com.calibre_ebook.calibre` to check if it has any effect?

**Comment by ImBearChild** [comment]
For example, in order to use Fcitx5 and performance well with KDE plasma in flatpak, there should be input method plugins for Qt, lying under`/usr/lib/plugins/platforminputcontexts/`,named `libfcitx5platforminputcontextplugin.so`,`plasmaimplatforminputcontextplugin.so` and `libqtvirtualkeyboardplugin.so` provided by KDE's runtime. But calibre flatpak only includes `libcomposeplatforminputcontextplugin.so` and `libibusplatforminputcontextplugin.so` under `/app/lib/calibre/plugins/platforminputcontexts`.

**Comment by Erick555** [comment]
> Simply run calibre with org.kde.Platform won't help, these library seems won't be loaded by Qt.

Hm, but you just asked for moving to org.kde.Platform and now you're saying it won't help?

**Comment by ImBearChild** [comment]
> Hm, but you just asked for moving to org.kde.Platform and now you're saying it won't help?

Sorry for that, I just thought it will help, because I didn't noticed that calibre using a built in Qt. I'm really sorry. :rofl:

**Comment by Erick555** [comment]
Flatpak doesn't build anything but uses official calibre binaries. Earlier you said that they [work on host](https://github.com/flathub/com.calibre_ebook.calibre/issues/126#issuecomment-1106359719) so I think they should work with flatpak as well. 

Could you try running `flatpak run --runtime=org.kde.Platform//5.15-21.08 --env=QT_PLUGIN_PATH="/app/lib/calibre/plugins:/usr/share/runtime/lib/plugins" com.calibre_ebook.calibre`

**Comment by ImBearChild** [comment]
Sorry again, I said "it's true", only because kovidgoyal said "input method plugins are typically provided by the host OS based on". I tried the [official calibre binaries](https://download.calibre-ebook.com/5.41.0/calibre-5.41.0-x86_64.txz) minutes ago, and it did not work with Fcitx5, even with additional `*contextplugin.so` copied to `calibre-5.41.0-x86_64/plugins/platforminputcontexts/`.

And `flatpak run --runtime=org.kde.Platform//5.15-21.08 --env=QT_PLUGIN_PATH="/app/lib/calibre/plugins:/usr/share/runtime/lib/plugins" com.calibre_ebook.calibre` don't work, too. This issue is not only applied to flatpak, but also official calibre binaries. Should I close this issue and open a new one for `bypy`?

**Comment by Erick555** [comment]
Yes, if it doesn't work outside flatpak then we can't fix it here.

**Comment by Iey4iej3** [comment]
Any workaround to use fcitx5?

**Comment by ImBearChild** [comment]
> Any workaround to use fcitx5?

Fcitx5 can be used with the iBus protocol, but it may have compatibility issues. For example, Fcitx5 popup is missing or at wrong position when typing.

**Comment by Iey4iej3** [comment]
Not sure how to do that. PS: I switched from ibus to fcitx5 due to the Wayland (sway) support of the later.

**Comment by ImBearChild** [comment]
> Not sure how to do that. PS: I switched from ibus to fcitx5 due to the Wayland (sway) support of the later.

This should be enough:

```
flatpak override --user --env=QT_IM_MODULE=ibus com.calibre_ebook.calibre
```
As for Fcitx5 itself, IBus protocol support is enable by default.

**Comment by Iey4iej3** [comment]
> > Not sure how to do that. PS: I switched from ibus to fcitx5 due to the Wayland (sway) support of the later.
> 
> This should be enough:
> 
> ```
> flatpak override --user --env=QT_IM_MODULE=ibus com.calibre_ebook.calibre
> ```
> 
> As for Fcitx5 itself, IBus protocol support is enabled by default.

Thanks. This works. However, the popup looks like XWayland — I enabled global scaling under Sway, and it does not work well for XWayland (blurry).
