### ISSUE TITLE
Can't access Kobo Clara HD (need access to /media)

### ISSUE THREAD

**Issue by dericke** [flathub/com.calibre_ebook.calibre#13]
When running the flatpak distribution of Calibre, I cannot normally access my Kobo Clara HD. I did not have a similar problem with the binary install on the Calibre website. Running the device debug, I found the message "UDisks not available on your system". I then tried running `flatpak --filesystem=/media run com.calibre_ebook.calibre`, which fixed the problem. Can the package request this permission by default? Thanks!

**Comment by TingPing** [comment]
Distro isn't relevant. It has permission `--filesystem=home` instead of `--filesystem=host`

**Comment by dericke** [comment]
This is on Ubuntu 18.04, which mounts removable storage devices in `/media` by default.

**Comment by dericke** [comment]
I believe `filesystem=host` would solve the problem as well, but that might be more broad than is needed. Based on the discussion at https://github.com/flatpak/flatpak/issues/2185, it appears that `/media`, /run/media`, and `/var/run/media` are all that Calibre would need to access without explicit user action.

**Comment by TingPing** [comment]
It is broad, but not in a meaningful way. Who cares that it can read `/foo` as well as `/media` really.

**Comment by dericke** [comment]
What other system directories does Calibre need access to?
