### ISSUE TITLE
Cannot set DARK_THEME as --env

### ISSUE THREAD

**Issue by hollisticated-horse** [flathub/com.calibre_ebook.calibre#132]
Hi, I've looked around and havn't found any info on how to set the env to CALIBRE_USE_DARK_PALETTE=1

I've tried: 
```
flatpak run --env=CALIBRE_USE_DARK_PALETTE=1 com.calibre_ebook.calibre
```
But it doesn't work, the theme stays white. 
Anyone know how to do this ?

**Comment by tinywrkb** [comment]
Add `CALIBRE_USE_SYSTEM_THEME=0`.
