### ISSUE TITLE
5.42.0 doesn't seem to be reaching me?

### ISSUE THREAD

**Issue by Kirtai** [flathub/com.calibre_ebook.calibre#133]
I see that this has been updated to version 5.42.0 but when I update my flatpaks it doesn't update and remains on 5.41.0

**Comment by Erick555** [comment]
yes, the CI job [wasn't triggered](https://flathub.org/builds/#/apps/com.calibre_ebook.calibre) after update was merged.

**Comment by Erick555** [comment]
New version should be published in few hours.

**Comment by Kirtai** [comment]
It's arrived. Thanks :)
