### ISSUE TITLE
Read Aloud doesn't work

### ISSUE THREAD

**Issue by faveoled** [flathub/com.calibre_ebook.calibre#151]
![image](https://user-images.githubusercontent.com/85760289/196216421-2e71d8ac-52cb-4891-9dbd-8f33c01fb71f.png)

**Comment by Erick555** [comment]
Do you install speech-dispatcher and is it running on your system (does `/run/user/1000/speech-dispatcher` exist?

**Comment by Erick555** [comment]
Did you restart the calibre?

**Comment by faveoled** [comment]
Yeah, multiple times

**Comment by Erick555** [comment]
Could you try running daemon as `speech-dispatcher -s -t0` the start calibre. Suggested [here](https://github.com/flathub/com.calibre_ebook.calibre/pull/65#issuecomment-735309081).

**Comment by faveoled** [comment]
> speech-dispatcher -s -t0

This one worked. My case can be closed.
