### ISSUE TITLE
Wrong version reported at Flathub

### ISSUE THREAD

**Issue by faveoled** [flathub/com.calibre_ebook.calibre#152]
Flathub reports 6.7.0 but 6.7.1 is installed

**Comment by Erick555** [comment]
This is because 6.7.1 wasn't properly tagged in upstream [chanagelog](https://github.com/kovidgoyal/calibre/commit/74208b5330a3a4650a11cc187fb4875b1b840baf), it's just mentioned there. Perhaps with next release it would work again.
