### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by lpinner** [flathub/com.calibre_ebook.calibre#158]
Pop!_OS 22.04 LTS Linux 6.0.6-76060006-generic x86_64
```
$ flatpak info com.calibre_ebook.calibre

calibre - The one stop solution to all your e-book needs

          ID: com.calibre_ebook.calibre
         Ref: app/com.calibre_ebook.calibre/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.9.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 454.5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: efd49f49d2ace896842392149a38355fcda8d0956740a4b1cec85bb0258db922
      Parent: ec50c128aa71d6ff2f2ad241b3346da06483245b506df9e4b726a0e0bdc65956
     Subject: Update 2 modules (06746424)
        Date: 2022-11-26 17:26:31 +0000
$ flatpak run com.calibre_ebook.calibre
```
Calibre fails to open. No errors are reported (unlike #157)

```
$ flatpak update --commit=6e6445c6e6e1087ceb8c3f64ff2d77624e91347f1094a3db76012f42f58ffb75 com.calibre_ebook.calibre

$ flatpak info com.calibre_ebook.calibre

calibre - The one stop solution to all your e-book needs

          ID: com.calibre_ebook.calibre
         Ref: app/com.calibre_ebook.calibre/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.7.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 454.4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 6e6445c6e6e1087ceb8c3f64ff2d77624e91347f1094a3db76012f42f58ffb75
      Parent: 13748def0a2f7a1b645fd43091d70e7d988a59297a568b0c3936426cb0beb1a1
     Subject: Use fallback-x11 (2d9f0848)
        Date: 2022-10-17 08:17:24 +0000
$ flatpak run com.calibre_ebook.calibre
```
However reverting to version using 21.08 runtime opens as expected.

**Comment by Erick555** [comment]
so `flatpak run com.calibre_ebook.calibre` just returns with no output in terminal? What if you start with empty `~/.var/app/com.calibre_ebook.calibre` (i.e. rename `com.calibre_ebook.calibre` to `com.calibre_ebook.calibre-backup`

**Comment by lpinner** [comment]
Yes, no output but nothing happens. Moving `~/.var/app/com.calibre_ebook.calibre` results in calibre opening with the fresh setup dialog.  

I closed calibre, copied `~/.var/app/com.calibre_ebook.calibre.backup` back and then calibre opened normally.  Weird, sorry for the noise.

**Comment by lpinner** [comment]
Note edited previous comment as I forgot to revert back to latest version (Version: 6.9.0 Commit: efd49f49d2ace896842392149a38355fcda8d0956740a4b1cec85bb0258db922) before trying the empty `~/.var/app/com.calibre_ebook.calibre`

**Comment by gestra** [comment]
I think I have the same issue, or at least something very similar, on Fedora 37. What makes it weird for me is that sometimes seemingly at random Calibre does start normally. I could try running it five times in a row, every time it failing to start and then on the sixth try it just starts.

My shell shows the return code "SIGSEGV" on failed startups.

Here's what I see in system logs:
[calibre_crash_log.txt](https://github.com/flathub/com.calibre_ebook.calibre/files/10215215/calibre_crash_log.txt)


```
> flatpak info com.calibre_ebook.calibre

calibre - The one stop solution to all your e-book needs

          ID: com.calibre_ebook.calibre
         Ref: app/com.calibre_ebook.calibre/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.9.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 454,5 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: efd49f49d2ace896842392149a38355fcda8d0956740a4b1cec85bb0258db922
      Parent: ec50c128aa71d6ff2f2ad241b3346da06483245b506df9e4b726a0e0bdc65956
     Subject: Update 2 modules (06746424)
        Date: 2022-11-26 17:26:31 +0000
```
```
> flatpak --version
Flatpak 1.14.0
```

**Comment by ghisvail** [comment]
> I think I have the same issue, or at least something very similar, on Fedora 37. What makes it weird for me is that sometimes seemingly at random Calibre does start normally. I could try running it five times in a row, every time it failing to start and then on the sixth try it just starts.

Same symptoms for me.

**Comment by Erick555** [comment]
Maybe it's worth asking about it on calibre upstream. Flatpak just repacks official binaries. The logs show something with openssl.

**Comment by alebastr** [comment]
```
#0  0x00007fc531c9d861 n/a (/usr/lib/x86_64-linux-gnu/libcrypto.so.3 + 0x29d861)
#1  0x00007fc531c2007f n/a (/usr/lib/x86_64-linux-gnu/libcrypto.so.3 + 0x22007f)
#2  0x00007fc55ec36840 n/a (/usr/lib/x86_64-linux-gnu/engines-3/pkcs11.so + 0x6840)
#3  0x00007fc55ec3694f n/a (/usr/lib/x86_64-linux-gnu/engines-3/pkcs11.so + 0x694f)
#4  0x00007fc5739a099b n/a (/app/lib/calibre/lib/libcrypto.so.1.1 + 0x1a099b)
...
```

The openssl version in the runtime (3.0.7) is too new for calibre. Bundled libcrypto (1.1.1l) reads `/etc/ssl/openssl.cnf` and attempts to load the pkcs11 engine built for 3.0, which is obviously not compatible with 1.1.

I verified that running calibre with 21.08 runtime works fine. Reverting the runtime update could resolve the issue.

Clearing the contents of `/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/active/files/etc/ssl/openssl.cnf` also works, but I don't believe this could be applied in the app manifest. I assume that adding `OPENSSL_CONF=/dev/null` to the environment overrides would achieve the same effect and could be used as a workaround.

**Comment by ghisvail** [comment]
It still does not explain why the app still successfully loads once every few times.

**Comment by Erick555** [comment]
22.08 is [required](https://github.com/flathub/com.calibre_ebook.calibre/pull/155) for aarch64 support so downgrade isn't feasible (it also has no future).

I can see two options:

1. Shipping openssl 1.1 compatible `openssl.cnf` file and setting `OPENSSL_CONF `accordingly.
2. Setting OPENSSL_CONF=/dev/null as proposed above.

I don't know if pkcs11 module has any purpose for calibre so the second option may be better one.

**Comment by Erick555** [comment]
I prepared https://github.com/flathub/com.calibre_ebook.calibre/pull/160 which should fix this.
