### ISSUE TITLE
Calibre not using System preferred application to open PDF file

### ISSUE THREAD

**Issue by ttjimera** [flathub/com.calibre_ebook.calibre#171]
I am running on Linux Mint Cinnamon 21.1. The system preferred application to open PDF file is set to Okular (Flatpak version). But when I open a PDF from Calibre, it opened the file using xreader instead. I tried opening from .deb version of Calibre and it opened the file correctly using Okular.

This is strange because both version of Calibre could open epub file correctly using Foliate (Flatpak version) which is the system preferred app to open epub file.

I am not sure if there are any permission I need to set in Flatseal in order to get Calibre Flatpak to honour the system preferred application.

**Comment by Erick555** [comment]
It should show the dialog listing all your pdf readers. You may need to reset some settings.

**Comment by ttjimera** [comment]
Where can I find this dialog with all the pdf readers? And can you please provide more details on the settings that need to be reset? Are these Calibre's settings or Flatpak's? Thanks.

**Comment by Erick555** [comment]
Flatpak settings - I think there are stored in `~/.local/share/flatpak/db`. Try removing it.

**Comment by ttjimera** [comment]
Thanks for the reply. But it does not help. After doing this, when I press Alt-V and then choose `Add other applications for PDF files`, it shows me only `Calibre` and `E-book viewer`. All the other PDF readers I have installed are not available to be selected. In the .deb version of Calibre, all the readers are available.

**Comment by ttjimera** [comment]
Ok, somehow it is now working. I was playing around with it trying many things. And then it suddenly showed me the dialog with all the PDF readers. I am not sure what it was I did that works. But I did notice that earlier when it did not work, `~/.local/share/flatpak/db` was not present after I deleted it. Now it has been regenerated. It took sometime before it was regenerated. Thanks for the help.
