### ISSUE TITLE
dedrm plugin unable to read kindle library

### ISSUE THREAD

**Issue by user5145** [flathub/com.calibre_ebook.calibre#18]
Please, consider adding --filesystem=/run/media permission. Dedrm plugin doesn't work nicely with kindle paperwhite without it (fails at "check for drm" or something like that and complains about read permission). I tested it only for read-write, so can't say about read-only permission.

The following line fixed the issue for me 
"flatpak --user override com.calibre_ebook.calibre --filesystem=/run/media"

**Comment by sat3ll** [comment]
Cases like these are to be handled by the user via manual override of permissions.
There was a proposal https://github.com/flatpak/flatpak/issues/2185 to add a `--filesystem=media` permission but it was shot down.
