### ISSUE TITLE
System font is ignored

### ISSUE THREAD

**Issue by monday15** [flathub/com.calibre_ebook.calibre#19]
Thanks for maintaining Calibre flathub package!

I have Roboto set as a system font, but Calibre ignores it and shows DejaVu Sans instead. Default sans font in ~/.config/fontconfg/fonts.conf is Liberation Sans (I assume, flatpak using this settings, because hinting, antialiasing, etc are are the same as in non-flatpak apps)  and I dont have any idea where does DejaVu comes from.

Small note: I don't use Calibre, only ebook-viewer app that comes with the bundle.

**Comment by TingPing** [comment]
Flatpak pulls in the system wide fontconfig settings, I don't think it touches private home configs.

**Comment by monday15** [comment]
I've checked calibre settings (in main app) and there is an option to change application font, it was set to DejaVu Sans 10 (by default), but, iirc, calibre from distro package follows system font settings.

**Comment by TingPing** [comment]
What happens if you copy `~/.config/fontconfg/fonts.conf` to `~/.var/app/com.calibre_ebook.calibre/config/fontconfig/fonts.conf`

**Comment by monday15** [comment]
@TingPing, I think nothing, because I've already changed font in application settings to Roboto, and I dont know how to revert that setting.

The problem is - flatpaked Calibre uses by default (for interface) either DejaVu Sans or default sans font instead of system interface font, while regular distro package (on Fedora, at least) uses font, that is set as interface font in system.

I have another qt5-app from flatpak, Focuswriter, it uses correct interface font, but it comes with qgnomeplatfrom + adwaita-qt theme (probably, it is the reason, why it uses correct interface font).

Anyway, feel free to close this, since it is very easy to change font in application settings.

**Comment by monday15** [comment]
I've checked Calibre from distro package - without qt5ct/qgnomeplatform it also uses default sans font for interface (gnome desktop), so there is no issue.
