### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/com.calibre_ebook.calibre#192]
Flathub allows changelogs for each new release - can these be automated?

**Comment by Erick555** [comment]
This depends on metadata provided by upstream. Nothing to do in packaging.

**Comment by Victor239** [comment]
It is indeed part of Flatpak packaging, you need an [appdata.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another Flatpak's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by ghisvail** [comment]
@Victor239 Indeed, Flathub can render release metadata.

Upstream is free to provide appstream metadata containing detailed changelog entries for each release so that downstream packaging efforts (including Flatpak) can benefit.

**Comment by Victor239** [comment]
I think I [found it here](https://github.com/kovidgoyal/calibre/blob/master/Changelog.txt) in a `txt` format. Some sort of script or GitHub Action could potentially be used to add entries to an `appdata` file.

**Comment by Erick555** [comment]
> It is indeed part of Flatpak packaging, you need an [appdata.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file.
> 
> See these examples of another Flatpak's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

calibre appdata comes directly from upstream, flatpak packaging doesn't touch it. You need to ask upstream to add changelog there.

**Comment by Victor239** [comment]
Ah, thought Flatpak packagers add it. My mistake.

**Comment by ghisvail** [comment]
Closing as won't fix on our side. Feel free to forward your request upstream 👍

**Comment by Victor239** [comment]
I think this issue can be reopened now, I've posted the [request upstream](https://bugs.launchpad.net/calibre/+bug/2037671) and they've provided information on how to obtain a `.metainfo.xml` file.

**Comment by ghisvail** [comment]
Please don't take it the wrong way, but when you get involved with issues like this, it is important to get your facts right **before** getting more people involved.

We do provide an appstream metadata file already:

```sh
$ find /var/lib/flatpak/app/com.calibre_ebook.calibre -name *.metainfo.xml 
/var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/e2122ddd8eb283573e23ebea48be9e19ada17fd760897e77bb4993c47c9b5f22/files/share/metainfo/calibre-ebook-viewer.metainfo.xml
/var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/e2122ddd8eb283573e23ebea48be9e19ada17fd760897e77bb4993c47c9b5f22/files/share/metainfo/calibre-ebook-edit.metainfo.xml
```

It's derived from the upstream one with the following post-install [steps](https://github.com/flathub/com.calibre_ebook.calibre/blob/ceaccd507d09824fad099c4cb22b03a5d7e2bc53/com.calibre_ebook.calibre.yaml#L72). So again, for your issue to be fixed, upstream needs to actually provide the appropriate release metadata in that file.

**Comment by ghisvail** [comment]
See this [section](https://freedesktop.org/software/appstream/docs/sect-Metadata-Releases.html) of the appstream docs for the format of the release metadata.

**Comment by Victor239** [comment]
I don't quite understand what's needed, would you be able to comment on the upstream issue with what needs to be changed?

**Comment by Erick555** [comment]
It turns out that upstream metainfo does have changelog data but it seems there is a bug with accidentally mangling it  -https://github.com/flathub/com.calibre_ebook.calibre/pull/194 should fix it.
