### ISSUE TITLE
Wrong icons in apps from the bundle

### ISSUE THREAD

**Issue by monday15** [flathub/com.calibre_ebook.calibre#20]
Ebook-viewer app (also checked ebook-editor) uses regular calibre icon instead of "a book with magnifying glass" (in gnome's dash/alt-tab switcher). In gnome's overview it has correct icon, but when you launch it, gnome shows that Calibre is currently running app, and ebook-viewer is not.

**Comment by sat3ll** [comment]
In KDE this doesn't happen (calibre version 4.6).
Can you retest?

**Comment by ghisvail** [comment]
Closing as invalid / not verifiable.

Please post a screenshot and details about your distribution, if the issue still persists today.
