### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-util

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.calibre_ebook.calibre#209]
The manifest uses `appstream-util modify`. Please try to convert it to patch

**Comment by ghisvail** [comment]
A little bit more context and explanation would come a long way here

**Comment by bbhtt** [comment]
> A little bit more context and explanation would come a long way here

https://github.com/flathub/com.calibre_ebook.calibre/blob/2d13713f74bf0b95af188ba8762a05a2f31a4607/com.calibre_ebook.calibre.yaml#L73-L76

**Comment by Erick555** [comment]
I think it's better to switch for `rename-appdata-file` function than patching

> rename-appdata-file (string)
> 
>     Any appdata (metainfo) file with this name will be renamed to a name based on id during the cleanup phase.

https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html

**Comment by bbhtt** [comment]
You need rename-desktop-file too, to update the launchable.
