### ISSUE TITLE
Don't show native available update dialog in Flatpak version

### ISSUE THREAD

**Issue by haevalencia** [flathub/com.calibre_ebook.calibre#221]
Hello. I just installed Calibre in flatpak version from the flathub repository and when starting, the first thing it shows is the native dialog that notifies about a new available update. I think it would be a good idea to disable this notification internally, since the flatpak update system is different and can confuse new users.

![Captura desde 2024-07-23 01-06-13](https://github.com/user-attachments/assets/14097348-6ee4-4f83-a267-eb6bd28f948e)

**Comment by Erick555** [comment]
In bottom of the dialog you have a checkbox for disabling notifications. I don't know if it's possible to disable this for all installations by default. Ideally flatpak would just always update to the latest - update is [ready](https://github.com/flathub/com.calibre_ebook.calibre/pull/220) but flathub decided to disable auto-updates recently so merging updates is manual action right now.

**Comment by ghisvail** [comment]
Le 23 juillet 2024 12:53:32 GMT+02:00, Erick555 ***@***.***> a écrit :
>In bottom of the dialog you have a checkbox for disabling notifications. I don't know if it's possible to disable this for all installations by default. Ideally flatpak would just always update to the latest - update is [ready](https://github.com/flathub/com.calibre_ebook.calibre/pull/220) but flathub decided to disable auto-updates recently so merging updates is manual action right now.
>

And I am away this week, so I can't merge the update at the moment.

Sorry
