### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by Dunhill69** [flathub/com.calibre_ebook.calibre#227]
error: Failed to install com.calibre_ebook.calibre/x86_64/stable: Error pulling from repo: While loading app/com.calibre_ebook.calibre/x86_64/stable from the remote flathub repository: Opening content object e6f5aaa18308ac65455a46844e2e34f3a730bff9c4f0ff38 82580c33f0f0cbd4: Opening content object e6f5aaa18308ac65455a46844e2e34f3a730bff9c4f0ff3882580c33f0f0cbd4 : Couldn't find file object 'e6f5aaa18308ac65455a46844e2e34f3a730bff9c4f0ff3882580c33f0f0cbd4')

**Comment by ghisvail** [comment]
Perhaps a temporary outage. Works fine with me today. Could you try again?

**Comment by Dunhill69** [comment]
> Quizás haya sido una interrupción temporal. A mí me funciona bien hoy. ¿Podrías intentarlo de nuevo?

installed again. thanks
