### ISSUE TITLE
Launches much more slowly than official binary

### ISSUE THREAD

**Issue by crispinb** [flathub/com.calibre_ebook.calibre#24]
On my system (ClearLinux v 31300, Gnome 3.34.1), the flatpak version of Calibre 4.1 is very slow to launch. It takes about 20s, during most of which time the main Calibre window's content is black. By comparison, the official 4.1 binary launches & populates the booklist in 1s at most.

**Comment by sat3ll** [comment]
`flatpak --version` ? Can you run `flatpak update`, `flatpak repair` and see if anything changes?

**Comment by crispinb** [comment]
> `flatpak --version` ?

Flatpak 1.4.3


> Can you run `flatpak update`, `flatpak repair` and see if anything changes?

Just tried - no change regrettably.

**Comment by ghisvail** [comment]
Does it happen on first launch only, or also in subsequent runs of the app ?

**Comment by crispinb** [comment]
I think it was every run - however I've shifted to a different Linux distro & am no longer using the flatpack so can't check.

**Comment by ghisvail** [comment]
I am not experiencing those significant slow down you are reporting. Initial launch after install is always slower but everything is fine after that.

**Comment by crispinb** [comment]
OK thanks - as I no longer have a Clear Linux system to check with, we might as well close this.
