### ISSUE TITLE
Which path for cmd-line utils is correct on flatpak installation?

### ISSUE THREAD

**Issue by AdmiralAsshat** [flathub/com.calibre_ebook.calibre#25]
A project I work on leverages the ebook-convert utility as part of its workflow. I ran a `locate ebook-convert` command to see where the flatpak version installs this binary, and I found several results.

```
[user@domain bin]$ locate ebook-convert
/var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/ebook-convert
/var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/bin/ebook-convert
/var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/resources/ebook-convert-complete.calibre_msgpack
[user@domain bin]$ ll /var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/ebook-convert
-rwxr-xr-x. 22 root root 6400 Oct  6 15:00 /var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/ebook-convert
[user@domain bin]$ ll /var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/bin/ebook-convert
-rwxr-xr-x. 2 root root 6328 Oct  6 15:00 /var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/96a03c3a4a53fff161502fc579e2a01249396edf3ce7f2b52ee9627d28ea44e6/files/bin/bin/ebook-convert
```

Is there a difference between the one in `/files/bin` and `/files/bin/bin`? They have slightly different filesizes. Which one should I be using if I want to make a symbolic link to it in /usr/bin?

**Comment by sat3ll** [comment]
You shouldn't symlink anything. Instead try `flatpak run --command=ebook-convert com.calibre_ebook.calibre`
Do remember to set adequate filesystem permissions (more can be found on flatpak docs).
Example of usage:
`$ flatpak run --command=ebook-convert com.calibre_ebook.calibre --version`
(command line arguments are placed at the end)

**Comment by AdmiralAsshat** [comment]
Hello! 

Thanks for the info. Regrettably, the tool is not mine, and I doubt I will be able to convince them to change it without a pretty convincing pull request.

You can take a look at the python script that invokes the tool [here](https://github.com/standardebooks/tools/blob/5cd588f3ad79a9ba37361ad13af0499d39ac5948/se/se_epub_build.py). The `shutil.which` command will fail unless the binary is found in one of the user's $PATH directories, hence the desire to sym-link.

It sounds like I may need to stick with my OS's normal installation repos, rather than the flatpak, if I want this to work.

**Comment by sat3ll** [comment]
You **could** try making a bash 'shim' script that acts as that symlink.
Or just follow the path of least resistance and use systemwide installs

**Comment by AdmiralAsshat** [comment]
Thanks! I will give the shim a try first, and go back to normal RPM installs if I can't get that to work.
