### ISSUE TITLE
Update for Calibre 4.9.0

### ISSUE THREAD

**Issue by byteshiva** [flathub/com.calibre_ebook.calibre#27]
Can you tell when the Update for Calibre 4.9.0 would be made available.

**Comment by ghisvail** [comment]
When someone provides a PR for it. Feel free to have a go at it.

**Comment by byteshiva** [comment]
@ghisvail  - I've raised a PR for update to 4.9.0, Can you please review and merge the changes.

**Comment by byteshiva** [comment]
@ghisvail  - I've raised a PR for update to 4.9.0, Can you please review and merge the changes.
