### ISSUE TITLE
doesn't start with "Could not initialize GLX"

### ISSUE THREAD

**Issue by bam80** [flathub/com.calibre_ebook.calibre#29]
Can't run the app:
```
$ flatpak run com.calibre_ebook.calibre
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (8 8 8 0)
...
Could not initialize GLX
```
The problem was reported here by someone else: https://bugs.launchpad.net/calibre/+bug/1850679

#26

**Comment by ghisvail** [comment]
I am not experiencing your issue on any of my machines. Sounds like this issue is specific to your distribution and setup.

Sadly, not much can be done without further details other than "can't run the app".

**Comment by bam80** [comment]
Here is my flatpak list: https://github.com/flathub/com.calibre_ebook.calibre/issues/26#issuecomment-578564631.
Could you past your? Maybe I miss some extensions..

**Comment by ghisvail** [comment]
> Sounds like this issue is specific to your distribution and setup.

Let's start with these details first.

AFAIC, I am not experiencing this issue on neither Debian stable nor testing.

**Comment by ghisvail** [comment]
You might want to test the latest update to version 4.10.1.

**Comment by bam80** [comment]
I'm running Slackware, Intel graphics.
I don't think Flatpak behavior should depend on the distro so much..
Anyway, I found the problem in this particular case, seems I used wrong Plasma runtime and the right one didn't auto-pulled for some reason..

**Comment by bam80** [comment]
@ghisvail still, can I ask you to help me with another similar problem?

> Could you also try to run org.kde.discover app from kdeapps repo?

https://github.com/flathub/com.calibre_ebook.calibre/issues/26#issuecomment-578564631

If it works for you, your `flatpak list` output would be useful.
Thanks.
