### ISSUE TITLE
File chooser is missing icons

### ISSUE THREAD

**Issue by garrett** [flathub/com.calibre_ebook.calibre#3]
The file selector for choosing a library location is missing icons:

![calibre-choose-lib](https://user-images.githubusercontent.com/10246/45412386-c0b0ab80-b676-11e8-9c83-0d5afaf303e5.png)

This is while using GNOME on Fedora 28.

---

Strangely, the file selector for adding a book is perfectly fine, with all the appropriate icons.

**Comment by ghisvail** [comment]
I am observing the same thing, indeed.

**Comment by ghisvail** [comment]
The file chooser works as intended though, so the issue is purely cosmetic.

**Comment by garrett** [comment]
While it is cosmetic, it does also get in the way of determining which locations are folders and which are files. It also causes problems with navigating directories. So it isn't purely a cosmetic issue.

**Comment by nedrichards** [comment]
It's this upstream issue in the FDo SDK. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/365 Once fixed there it'll work on all apps that use the 18.08 runtime.

**Comment by ghisvail** [comment]
Thanks @nedrichards for your pointers on this issue.

**Comment by ghisvail** [comment]
It looks fine now.
