### ISSUE TITLE
Cannot convert EPUB books to MOBI

### ISSUE THREAD

**Issue by LaHaine** [flathub/com.calibre_ebook.calibre#30]
This was first reported to the upstream bug tracker:
https://bugs.launchpad.net/calibre/+bug/1861625

If you convert a book from EPUB to MOBI, no output file is written, this is caused by some permission problem.  Just the conversation output is printed without an actual error:
```

Konvertierungsfehler: Fehlgeschlagen: Buch 1 von 1 (Artificial Condition) konvertieren

Buch 1 von 1 (Artificial Condition) konvertieren
Conversion options changed from defaults:
  output_profile: u'kindle_pw3'
  cover: u'/tmp/calibre_4.9.0_tmp_JLD7Pp/taKGAY.jpeg'
  verbose: 2
  read_metadata_from_opf: u'/tmp/calibre_4.9.0_tmp_JLD7Pp/ePkaCy.opf'
Resolved conversion options
calibre version: 4.9.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_4.9.0_tmp_JLD7Pp/taKGAY.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7fcf62151550>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x7fcf62151d50>,
 'page_breaks_before': u'/',
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_4.9.0_tmp_JLD7Pp/ePkaCy.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on /tmp/calibre_4.9.0_tmp_JLD7Pp/D0iu_b.epub
Found HTML cover OEBPS/xhtml/cover.xhtml
Parsing all content...
Parsing OEBPS/xhtml/cover.xhtml ...
Parsing OEBPS/xhtml/title.xhtml ...
Parsing OEBPS/xhtml/mini_toc.xhtml ...
Parsing OEBPS/xhtml/chapter2.xhtml ...
Parsing OEBPS/xhtml/copyright.xhtml ...
Parsing OEBPS/xhtml/chapter3.xhtml ...
Parsing OEBPS/xhtml/chapter1.xhtml ...
Parsing OEBPS/xhtml/chapter4.xhtml ...
Parsing OEBPS/xhtml/chapter5.xhtml ...
Parsing OEBPS/xhtml/chapter7.xhtml ...
Parsing OEBPS/xhtml/chapter6.xhtml ...
Parsing OEBPS/xhtml/chapter8.xhtml ...
Parsing OEBPS/xhtml/copyrightnotice.xhtml ...
Parsing OEBPS/xhtml/adcard.xhtml ...
Parsing OEBPS/xhtml/chapter9.xhtml ...
Parsing OEBPS/xhtml/abouttheauthor.xhtml ...
Parsing OEBPS/xhtml/torad.xhtml ...
Parsing OEBPS/xhtml/newsletter.xhtml ...
Parsing OEBPS/xhtml/contents.xhtml ...
Parsing OEBPS/styles/stylesheet.css ...
Parsing OEBPS/nav.xhtml ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 18 items of level: div_1
Found 894 items of level: p_2
div_1 left margin stats: Counter({u'0': 15})
div_1 right margin stats: Counter({u'0': 15})
p_2 left margin stats: Counter({u'0': 894})
p_2 right margin stats: Counter({u'0': 894})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'OEBPS/xhtml/cover.xhtml' from manifest
Trimming u'OEBPS/toc.ncx' from manifest
Trimming u'OEBPS/nav.xhtml' from manifest
Creating MOBI Output...
Serializing resources...
libpng warning: iCCP: known incorrect sRGB profile
Creating MOBI 6 output
Applying case-transforming CSS...
Parsing manglecase.css ...

```

The conversion is working fine with calling the converter directly:
`% /var/lib/flatpak/app/com.calibre_ebook.calibre/x86_64/stable/active/files/bin/ebook-convert x.epub x.mobi
`
This was with Ubuntu 18.04 and Calibre 4.9.0 from your Flatpak.

Edit: so this command doesn't work either:
`% flatpak run --command=ebook-convert com.calibre_ebook.calibre x.epub x.mobi`

**Comment by Erick555** [comment]
I can confirm that epub->modi doesn't work although some others like azw3->epub do. It doesn't look like permission issue, maybe some dependency is missing?

**Comment by LaHaine** [comment]
If you call the binary directly as mentioned in my initial report, the conversion works, just not if called from flatpak.

**Comment by Erick555** [comment]
@LaHaine no, if you call binary directly as you mentioned you are using all binaries and libraries from host and not those available in flatpak.

**Comment by eli-schwartz** [comment]
The flatpak reuses the upstream prebuilt binaries which are totally standalone and use their own vendored libraries for everything. As long as some generally compatible libc and libstdc++ is available, it will run.

If the problem was actually missing dependencies, then where is the missing shared library error message?

Whatever the problem is, it is being caused by the sandbox, but it's unlikely to be in any way dependency related.

**Comment by Erick555** [comment]
Well, there is no meaningful error message at all, it just stops running after creating some files in /tmp.  I don't see what can be done with sandbox here but it would be nice to know how exactly conversion is one and why mobi is different from other formats.

**Comment by Erick555** [comment]
I found that selecting `new` MOBI file type in convert options makes conversion successful. It fails for `old` and `both` options.

**Comment by eli-schwartz** [comment]
Does PDF work?

**Comment by Erick555** [comment]
@eli-schwartz no, converting anything to pdf fails:

```
Conversion options changed from defaults:
  disable_font_rescaling: True
  cover: u'/tmp/calibre_4.9.0_tmp_yhBASU/Fb96kK.jpeg'
  change_justification: u'justify'
  verbose: 2
  pdf_sans_family: u'Liberation Sans'
  output_profile: u'kindle_pw'
  input_profile: u'kindle'
  no_chapters_in_toc: True
  pdf_serif_family: u'Liberation Serif'
  read_metadata_from_opf: u'/tmp/calibre_4.9.0_tmp_yhBASU/hh5SkK.opf'
  page_breaks_before: u'/'
  remove_fake_margins: False
  pdf_mono_family: u'Liberation Mono'
Resolved conversion options
calibre version: 4.9.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'justify',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_4.9.0_tmp_yhBASU/Fb96kK.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': True,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.KindleInput object at 0x682539b1f9d0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': True,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x682539b34050>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_4.9.0_tmp_yhBASU/hh5SkK.opf',
 'remove_fake_margins': False,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
```

**Comment by eli-schwartz** [comment]
Then my guess is something is breaking the qt5-webengine rendering process which is run using a qt QPA "headless" plugin. The PDF Output plugin definitely does this, I cannot remember offhand whether or why the Mobi Output plugin does, possibly in order to re-render the cover image?

Did this work on pre-4.x versions of the flatpak?

Does the flatpak provide a working libGL.so (which should pull in libGLX.so and therefore libX11.so)? Because any components of calibre which need the headless plugin or otherwise use QtGui will need access to this (and calibre doesn't provide its own libGL and libX11 because that needs to interact with the system one).

**Comment by LaHaine** [comment]
That would explain this error message in the kernel log:
```
[42565.377830] Progress[5084]: segfault at 20 ip 00007fcf5a0973d8 sp 00007ffcf79e9068 error 4 in libqxdgdesktopportal.so[7fcf5a092000+10000]
[42565.377835] Code: 00 00 48 8b 47 10 48 8b 78 10 48 8b 07 48 8b 40 40 ff e0 90 0f 1f 40 00 66 2e 0f 1f 84 00 00 00 00 00 48 8b 47 10 48 8b 78 10 <48> 8b 07 48 8b 40 48 ff e0 90 0f 1f 40 00 66 2e 0f 1f 84 00 00 00
```

**Comment by Erick555** [comment]
Doesn't ebook-viewer use the same qt5-webengine rendering process? Viewing ebooks in various formats works for me.

> Does the flatpak provide a working libGL.so (which should pull in libGLX.so and therefore libX11.so)?

Yes

**Comment by Erick555** [comment]
@LaHaine this doesn't look related, also it doesn't occur for me.

**Comment by eli-schwartz** [comment]
> Doesn't ebook-viewer use the same qt5-webengine rendering process? Viewing ebooks in various formats works for me.

It does, and any graphical interface must make use of libGL.so via QtGui -- not being a flatpak user, I have no idea whether different entry points may have different permissions. ebook-convert is "expected" to be a command-line program, for all I know, it may not have as many permissions.

The only thing I can think of as special for PDF output (broken), which is not present in AZW3 output (works) is the webengine stuff.

**Comment by Erick555** [comment]
There is only one set or permissions which is applicable to whole flatpak container, they aren't per-binary.

**Comment by Erick555** [comment]
> That would explain this error message in the kernel log:
> 
> ```
> [42565.377830] Progress[5084]: segfault at 20 ip 00007fcf5a0973d8 sp 00007ffcf79e9068 error 4 in libqxdgdesktopportal.so[7fcf5a092000+10000]
> [42565.377835] Code: 00 00 48 8b 47 10 48 8b 78 10 48 8b 07 48 8b 40 40 ff e0 90 0f 1f 40 00 66 2e 0f 1f 84 00 00 00 00 00 48 8b 47 10 48 8b 78 10 <48> 8b 07 48 8b 40 48 ff e0 90 0f 1f 40 00 66 2e 0f 1f 84 00 00 00
> ```

Wait, this indeed occurs while using ebook-convert from cmdline. Debug symbols are stripped though so there is not much info:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe50283d8 in ?? () from /app/bin/plugins/platformthemes/libqxdgdesktopportal.so
```

I found out that simply removing `/app/bin/plugins/platformthemes/libqxdgdesktopportal.so` makes all conversions working again.
@LaHaine @eli-schwartz

**Comment by kovidgoyal** [comment]
MOBI output will use Qt for rasterizing SVG images since MOBI does not support SVG. And the PDF backend uses webengine and Qt for rendering HTML to PDF. Presumably Qt in turn uses xdgdesktopportal plugin which breaks when running inside the flatpak container.

**Comment by kovidgoyal** [comment]
Although I dont really understand why it should break for CLI processes but not GUI ones. Probably security related to X cookies or some such?? No idea how flatpak does containerization.

**Comment by kovidgoyal** [comment]
The difference between GUI and CLI apps is that the latter use the headless qt plugin. Presumably that plugin needs to somehow intercept and prevent calls to xdg portal, possibly by overriding some more methods

**Comment by Erick555** [comment]
I created https://github.com/flathub/com.calibre_ebook.calibre/pull/31 which should fix this issue.

**Comment by Erick555** [comment]
Unfortunately removing `libqxdgdesktopportal.so` breaks file-chooser portal so it can't be simply removed.

**Comment by Erick555** [comment]
> The difference between GUI and CLI apps is that the latter use the headless qt plugin. Presumably that plugin needs to somehow intercept and prevent calls to xdg portal, possibly by overriding some more methods

My current theory is that it calls portal instead of processing files directly which is unwanted in this context and also fails.

**Comment by kovidgoyal** [comment]
This *might* help https://github.com/kovidgoyal/calibre/commit/652841175d36e491fd378e15f608b4a68d711e1c

**Comment by Erick555** [comment]
@kovidgoyal thx, I'll wait for new release to test.

**Comment by Erick555** [comment]
@LaHaine @kovidgoyal I confirmed that update to 4.10.1 fixes conversion to mobi and pdf, thx for help.
