### ISSUE TITLE
Calibre notifications show no icon

### ISSUE THREAD

**Issue by ThracianKnight1907** [flathub/com.calibre_ebook.calibre#38]
Title says it all.

**Comment by ghisvail** [comment]
> Title says it all.

No, it does not.

What system are you running? (distro, desktop environment, flatpak version)

**Comment by ThracianKnight1907** [comment]
Sorry, forgot to add them:
Fedora 32
Gnome 3.36.2
Flatpak v 1.6.3
Calibre v 4.15
I have no extensions related to notifications

**Comment by sat3ll** [comment]
How do you reproduce this? (How to trigger a notification from calibre?)

**Comment by ThracianKnight1907** [comment]
Converting books, syncing them to an e-reader... there are probably more but these are the ones i encountered

**Comment by ghisvail** [comment]
Can anyone reproduce this issue on the latest version and provide a screenshot?

**Comment by ThracianKnight1907** [comment]
![Captură de ecran de la 2020-10-31 21-25-18](https://user-images.githubusercontent.com/64692701/97788205-f222c300-1bbf-11eb-8dbe-09492acfe4fa.png)
Hello, this is a screen capture with the latest calibre flatpak (5.4.2)

**Comment by ghisvail** [comment]
This is still on Fedora correct?

**Comment by ThracianKnight1907** [comment]
Yes,
Fedora 33
Gnome 3.38.1
Flatpak v 1.8.2

**Comment by ghisvail** [comment]
I can reproduce this on Debian. Though I am not sure how this is supposed to look like normally (never paid attention to calibre notifications before).
