### ISSUE TITLE
Calibre icon is missing on Flathub.org

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.calibre_ebook.calibre#4]
It looks like that the icon for calibre is missing on the [Flathub page](https://flathub.org/apps/details/com.calibre_ebook.calibre). Probably some AppStream issue?

**Comment by Erick555** [comment]
See https://github.com/flathub/com.calibre_ebook.calibre/issues/1#issuecomment-420411251 and below.

**Comment by ghisvail** [comment]
@nedrichards I should have an [icon](https://github.com/flathub/com.calibre_ebook.calibre/blob/a523ef916d0ea7cc2497b2590f56306e9ac9b0b1/com.calibre_ebook.calibre.yaml#L20) installed which matches the app-id.

**Comment by nedrichards** [comment]
You're not wrong.

**Comment by Erick555** [comment]
But there is icon with app-id [com.calibre_ebook.calibre.png](https://github.com/flathub/com.calibre_ebook.calibre/blob/a523ef916d0ea7cc2497b2590f56306e9ac9b0b1/com.calibre_ebook.calibre.yaml#L20).

**Comment by TingPing** [comment]
> But there is icon with app-id com.calibre_ebook.calibre.png

Well if its unused that doesn't really make sense.

> Moreover the non-app-id main icon (with gui suffix) is artificial and can be dropped as it may do more harm than good.

Likely true. It is a decision upstream should be deciding honestly.

**Comment by Pixelnarium** [comment]
Could it be that this also confuses GNOME? For me this (and only this so far) flatpak thinks it's part of the last flatpaked application used. To explain it: Let's start KeePassXC. Now start Calibre. In the top left GNOME now still shows "KeePassXC". Also Alt+Tab thinks that both windows are owned by KeePassXC. And it does not matter what flatpaked application I start first, it still thinks it belongs to that.

![bildschirmfoto vom 2018-09-15 09-37-33](https://user-images.githubusercontent.com/30435935/45583966-9d326e80-b8cb-11e8-9077-93a35dc630a6.png)

![bildschirmfoto vom 2018-09-15 09-37-50](https://user-images.githubusercontent.com/30435935/45583967-9f94c880-b8cb-11e8-9368-22d80e9136bf.png)

**Comment by AsciiWolf** [comment]
Calibre also seems to be missing in GNOME Software.

**Comment by ghisvail** [comment]
The icon is now displayed on flathub.
