### ISSUE TITLE
No SSL for python inside container

### ISSUE THREAD

**Issue by dcbaker** [flathub/com.calibre_ebook.calibre#6]
I've installed a callibre plugin, [fanficfare](https://github.com/JimmXinu/FanFicFare), which is used to download stories from various sites and convert them to epubs. Sites that lack encryption work fine, but any site with https fails with an SSL error

Here's the error log using one of the demo pages:
```
Status
Title
Author
Comment
URL
Bad
Unknown
Unknown
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
https://archiveofourown.org/works/123456
```

**Comment by ghisvail** [comment]
Do you happen to know what calibre uses to support SSL?

**Comment by dcbaker** [comment]
In this case I'm pretty sure that it's python itself throwing the SSL error, and python uses OpenSSL. What this looks more like to me is that there aren't certificates in the container or that they're not where python expects them to be. Which might actually be a problem with the underlying platform/sdk.

**Comment by TingPing** [comment]
Please report this to the runtime: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

With a minimal Python reproducer.

**Comment by kiklop74** [comment]
I did report the issue and their investigation uncovered that it is a calibre flatpak issue. freedesktop-sdk ships with all needed certificates but python binary shipped with Calibre does not detect them for whatever reason (probably looks in the wrong place).

See here
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/442

So ball is back in your court.

**Comment by TingPing** [comment]
Ok then Calibre must be changing the default configuration on the urlopener somewhere.

**Comment by sat3ll** [comment]
@dcbaker If this still occurs can you try `flatpak run --env=SSL_CERT_DIR=/etc/ssl/certs com.calibre_ebook.calibre` ?

**Comment by trochdewei** [comment]
> Have same issue - unable to fetch metadata for books

After the last update, the problem is gone
