### ISSUE TITLE
Trashed files stay sandboxed

### ISSUE THREAD

**Issue by nbriche** [flathub/com.calibre_ebook.calibre#83]
Calibre makes heavy use of the trash. On my install though, Calibre sees the trash in `~/.var/app/com.calibre_ebook.calibre/data/Trash`, not the user's `~/.local/share/Trash`.

This means that Calibre's trash aren't managed by the desktop UI, and a heavy-ish user could be wondering what is eating those hundreds of MBs and how to reclaim the space.

My current solution is to use trash-cli:
`$ XDG_DATA_HOME=~/.var/app/com.calibre_ebook.calibre/data trash-empty`

It works and I'm sure if I made the slightest effort I could even put that in a cron, but it would be cleaner if Calibre could be allowed to access the global trash.

I'm pretty new to flatpaks though, so I don't know what would be necessary to achieve this. I've run across references to "portal" APIs, including an API for the trash. But I don't know what is supposed to actually implement those APIs: upstream (unlikely?), runtime, something in the flatpak's build?

My system: Ubuntu 20.10, GNOME session, Flatpak Calibre 5.13; xdg-desktop-portal 1.8.0, xdg-desktop-portal-gtk but no xdg-desktop-portal-kde

**Comment by Erick555** [comment]
You can try with `flatpak run --filesystem=xdg-data/Trash com.calibre_ebook.calibre` or `flatpak --user --override --filesystem=xdg-data/Trash com.calibre_ebook.calibre` to make it persistent.

**Comment by nbriche** [comment]
Your solution works perfectly. Thanks you!
