### ISSUE TITLE
unable to retrieve metadata because of ssl errors

### ISSUE THREAD

**Issue by hammerandtongs** [flathub/com.calibre_ebook.calibre#89]
The flatpak on debian testing circa 6/2021 is unable to access metadata because of ssl errors.

> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

This seems related to #6 and possibly something to do with 

https://github.com/flatpak/flatpak/issues/2721

Possibly specifically 

https://github.com/flatpak/flatpak/issues/2721#issuecomment-660148315

When launching the flatpak with 

`flatpak run --env=SSL_CERT_DIR=/etc/ssl/certs com.calibre_ebook.calibre`

The metadata retrieval works fine. The easiest way to fix this for a user is to just use flatseal to add that environment variable.

Putting "import requests; print(requests.certs.where())" somewhere in the python might be interesting or it might be misleading depending on the actual libraries used.

**Comment by ghisvail** [comment]
Maybe I could add `--env=SSL_CERT_DIR=/etc/ssl/certs` to `finish-args`. It's exposed to other Flatpak apps such as [TeamSpeak](https://github.com/flathub/com.teamspeak.TeamSpeak/blob/4d395898afa18b1d83db96d4513d1dec4e001478/com.teamspeak.TeamSpeak.yaml#L16) and [Steam](https://github.com/flathub/com.valvesoftware.Steam/blob/e33a20a2701194a16ad483de3a953197d8a5acc2/com.valvesoftware.Steam.yml#L65).

**Comment by ghisvail** [comment]
Checked with the Flatpak IRC support channel, it's fine to add.
